---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here

    - name: "install python for Ansible."
      # Your code here

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'postgres')}}"  
    - TYPEORM_ENTITIES: "{{ lookup('env', './modules/domain/**/*.entity{.ts,.js}')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'udapeople-prod')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'postgres')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'udapeople123')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'udapeople-prod')}}"
   
  roles:
    # Your code here
