---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade package"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: [ 'nodejs', 'npm' ]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "configure environment variables"
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

- name: "configure pm2 to run server"
  shell: |
    pm2 start npm --name backend -- start
    echo "Done"
  register: results

- name: print messages
  debug:
    msg: "{{ results.stdout_lines }}"



