---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade package"
  become: yes
  apt:
    upgrade: 'yes'

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "configure migration"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migration_results.txt
    curl -H "Content-Type: text/plain" -H "token: {{ TOKEN }}" --request PUT \
      --data "1" https://api.memstash.io/values/migration_{{ TOKEN }}

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "starting pm2"
  shell: |
    sudo env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu



