---
- name: Copy backend tar.gz file and unzipping it
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: start pm2
  become: yes
  command: chdir=/home/ubuntu/backend /usr/local/bin/pm2 start --name "backend" npm -- start