---
- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend tar.gz file and unzipping it
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend
    list_files: yes

- name: install dependencies
  become: yes
  npm:
    path: /home/ubuntu/backend

- name: build backend
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm build
    npm start:prod