---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz
    
    # add extra code ends ----------
- name: extract backend files
  become: true
  shell: |
    cd /home/ubuntu
    tar -vxf backend.tar.gz
    rm backend.tar.gz

#- name: start node
 # become: true
  #shell: |
   # cd /home/ubuntu
    #npm install
    #pm2 stop default
    # pm2 start npm -- start
  # add extra code ends ----------
  
- name: "installing dependencies"
  become: yes
  npm:
    path: /home/ubuntu/backend

- name: "run migration"
  become: yes
  shell: npm run migrations
  args:
    chdir: /home/ubuntu/backend

- name: "reboot server"
  become: yes
  reboot:

- name: "initialize pm2"
  become: yes
  shell: pm2 ls
  args:
    chdir: /home/ubuntu/backend

- name: "start pm2"
  become: yes
  shell: pm2 start --name "backend" npm -- start
  args:
    chdir: /home/ubuntu/backend
